- name: Enable Apache SSL module
  command: a2enmod ssl creates=/etc/apache2/mods-enabled/ssl.load

- name: Enable NameVirtualHost for HTTPS
  lineinfile: dest=/etc/apache2/ports.conf regexp='^    NameVirtualHost \*:443' insertafter='^<IfModule mod_ssl.c>' line='    NameVirtualHost *:443'

- name: Add common Apache SSL config
  template:
    src=etc_apache2_ssl.conf.j2
    dest=/etc/apache2/ssl.conf
    owner=root
    group=root

- name: add ssl-cert user
  user: name=ssl-cert group=ssl-cert

- name: install simp_le OS deps
  apt: name={{ item }}
  with_items:
    - ca-certificates
    - python-pip
    - python-dev

- name: install simp_le python dep acme
  pip: name=acme version=0.1.0

- name: get simp_le python file
  get_url:
    url=https://raw.githubusercontent.com/kuba/simp_le/master/simp_le.py
    dest=/usr/local/bin/simp_le
    mode=0755
    owner=root
    group=root
